services:
  ioc:
    image: ghcr.io/cnpem/ad-sim-epics-ioc
    build:
      context: ./
      target: dynamic-link
      dockerfile: docker/Dockerfile
      labels:
        org.opencontainers.image.source: https://github.com/cnpem/ad-sim-epics-ioc
      args:
        REPONAME: ad-sim-epics-ioc
        RUNTIME_PACKAGES: libxml2
        RUNDIR: /opt/ad-sim-epics-ioc/iocBoot/iocsimulator
        ENTRYPOINT: ./run.sh
